In [1]:
#Biblitecas iniciais
import numpy as np
import pandas as pd

In [2]:
#Carregamento dos dados
df = pd.read_csv('https://raw.githubusercontent.com/wellingtondantas/Data-Science/master/Datasets/covid_pre_condition.csv')
df

id  sex  patient_type  ... contact_other_covid covid_res icu
0       16169f    2             1  ...                   2         1  97
1       1009bf    2             1  ...                  99         1  97
2       167386    1             2  ...                  99         1   2
3       0b5948    2             2  ...                  99         1   2
4       0d01b5    1             2  ...                  99         1   2
...        ...  ...           ...  ...                 ...       ...  ..
566597  01ff60    2             1  ...                   2         3  97
566598  047cd1    1             1  ...                   2         3  97
566599  1beb81    1             2  ...                  99         3   2
566600  16fb02    1             1  ...                   2         3  97
566601  0021c9    2             1  ...                   2         3  97

[566602 rows x 23 columns]

In [3]:
#Retira as colunas não essenciais
df=df.drop(columns=['id','entry_date','date_symptoms','date_died'],axis=1)
df

sex  patient_type  intubed  ...  contact_other_covid  covid_res  icu
0         2             1       97  ...                    2          1   97
1         2             1       97  ...                   99          1   97
2         1             2        2  ...                   99          1    2
3         2             2        2  ...                   99          1    2
4         1             2        2  ...                   99          1    2
...     ...           ...      ...  ...                  ...        ...  ...
566597    2             1       97  ...                    2          3   97
566598    1             1       97  ...                    2          3   97
566599    1             2        2  ...                   99          3    2
566600    1             1       97  ...                    2          3   97
566601    2             1       97  ...                    2          3   97

[566602 rows x 19 columns]

In [4]:
#Transfere as informações para outra base
dfe = df

# **Limpeza de dados**

In [5]:
#Substituindo 97, 98, 99 para valores nulos e excluindo
#Porém, na idade, realmente uma pessoa pode ter 97,98,99 anos
dfe.iloc[:,5:]=dfe.iloc[:,5:].replace({97:np.nan,98:np.nan,99:np.nan})
dfe=dfe.dropna()
dfe

sex  patient_type  intubed  ...  contact_other_covid  covid_res  icu
21        1             2        2  ...                  1.0        1.0  2.0
30        1             2        2  ...                  1.0        1.0  2.0
71        1             2        2  ...                  1.0        1.0  2.0
79        1             2        1  ...                  1.0        1.0  2.0
93        1             2        2  ...                  1.0        1.0  2.0
...     ...           ...      ...  ...                  ...        ...  ...
566497    1             2        2  ...                  1.0        3.0  2.0
566499    1             2        2  ...                  1.0        3.0  2.0
566543    1             2        2  ...                  2.0        3.0  2.0
566559    1             2        2  ...                  2.0        3.0  2.0
566578    1             2        1  ...                  1.0        3.0  2.0

[23158 rows x 19 columns]

In [6]:
dfe1=dfe[dfe['icu']==2][1:3000]
dfe2=dfe[dfe['icu']==1][1:2695]
frames=[dfe1,dfe2]
dfe3=pd.concat(frames)
dfe3=dfe3.sample(frac=1)
dfe3

sex  patient_type  intubed  ...  contact_other_covid  covid_res  icu
45973     1             2        2  ...                  1.0        1.0  2.0
17766     1             2        2  ...                  2.0        1.0  2.0
14072     1             2        2  ...                  1.0        1.0  2.0
56936     1             2        1  ...                  2.0        1.0  2.0
16280     1             2        2  ...                  1.0        1.0  2.0
...     ...           ...      ...  ...                  ...        ...  ...
186096    1             2        2  ...                  2.0        1.0  1.0
25555     1             2        2  ...                  2.0        1.0  2.0
196577    1             2        1  ...                  1.0        1.0  1.0
56946     1             2        2  ...                  2.0        1.0  2.0
40563     1             2        2  ...                  1.0        1.0  1.0

[5693 rows x 19 columns]

In [7]:
#Reseta os indices
dfe3 = dfe3.reset_index()

#Excluir os index anteriores
dfe3 = dfe3.drop(columns=['index'],axis=1)
dfe3

sex  patient_type  intubed  ...  contact_other_covid  covid_res  icu
0       1             2        2  ...                  1.0        1.0  2.0
1       1             2        2  ...                  2.0        1.0  2.0
2       1             2        2  ...                  1.0        1.0  2.0
3       1             2        1  ...                  2.0        1.0  2.0
4       1             2        2  ...                  1.0        1.0  2.0
...   ...           ...      ...  ...                  ...        ...  ...
5688    1             2        2  ...                  2.0        1.0  1.0
5689    1             2        2  ...                  2.0        1.0  2.0
5690    1             2        1  ...                  1.0        1.0  1.0
5691    1             2        2  ...                  2.0        1.0  2.0
5692    1             2        2  ...                  1.0        1.0  1.0

[5693 rows x 19 columns]

# **Analise dos dados**

In [8]:
#Verifica a quantidade de pessoas encaminhas para a UTI
dfe3['icu'].value_counts()

2.0    2999
1.0    2694
Name: icu, dtype: int64

In [9]:
#Separa o conjunto em features (X) e targets (Y)
X = dfe3.iloc[:,:-1]
Y = dfe3.iloc[:,-1]
X.shape, Y.shape

((5693, 18), (5693,))

In [10]:
#A função (train_test_split) os dados de treinamento e teste:  
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [11]:
#Apresentação das dimensões dos conjuntos criados
print('\n', X_train.shape) 
print('\n', Y_train.shape) 
print('\n', X_test.shape) 
print('\n', Y_test.shape)
print('\n')

#Balanceamento de dados
#Treinamento
print(' {0} : ({1}%)'.format(1, (sum(Y_train == 1)/len(Y_train))*100))
print(' {0} : ({1}%)'.format(2, (sum(Y_train == 2)/len(Y_train))*100))

#Teste
print(' {0} : ({1}%)'.format(1, (sum(Y_test == 1)/len(Y_test))*100))
print(' {0} : ({1}%)'.format(2, (sum(Y_test == 2)/len(Y_test))*100))


 (4554, 18)

 (4554,)

 (1139, 18)

 (1139,)


 1 : (47.10144927536232%)
 2 : (52.89855072463768%)
 1 : (48.20017559262511%)
 2 : (51.79982440737489%)


In [12]:
#Bibliotecas de importantes
import random
import matplotlib.pyplot as plt


#Bibliotecas de metricas
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [13]:
#Classificador KNN
from sklearn.neighbors import KNeighborsClassifier

#avaliação para KNN
realizacoes = 20

#Matriz que vai salvar medidas de cada realização
scoresKNN = np.zeros([realizacoes,4])

for item in range(realizacoes):
  X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=random.randrange(0, 101, 2))
  neigh = KNeighborsClassifier(n_neighbors=3)
  neighb=neigh.fit(X_train,Y_train)
  Y_pred=neighb.predict(X_test)
  scoresKNN[item,0] = accuracy_score(Y_test,Y_pred)
  scoresKNN[item,1] = f1_score(Y_test,Y_pred, average='weighted')
  scoresKNN[item,2] = recall_score(Y_test,Y_pred, average='micro')
  scoresKNN[item,3] = precision_score(Y_test,Y_pred, average='weighted')

  print('Score {0} : F1 {1} : Recall {2} : Precision {3}'.format(scoresKNN[item,0], scoresKNN[item,1], scoresKNN[item,2], scoresKNN[item,3]))

print('Métricas')
metricsKNN = pd.DataFrame(scoresKNN, columns=['Accuracy', 'F1', 'Recall', 'Precision'])
print(metricsKNN.mean()*100)
confusion_matrix(Y_test,Y_pred)

Score 0.7348551360842844 : F1 0.731329175442967 : Recall 0.7348551360842844 : Precision 0.7381784363711607
Score 0.7225636523266022 : F1 0.7168283213015043 : Recall 0.7225636523266022 : Precision 0.7291718664204063
Score 0.7287093942054433 : F1 0.7260262408560096 : Recall 0.7287093942054433 : Precision 0.7333224074571516
Score 0.7568042142230026 : F1 0.7542222736351818 : Recall 0.7568042142230026 : Precision 0.7611692986148382
Score 0.7357330992098332 : F1 0.7304225946603908 : Recall 0.7357330992098332 : Precision 0.7438364642025447
Score 0.7287093942054433 : F1 0.7260262408560096 : Recall 0.7287093942054433 : Precision 0.7333224074571516
Score 0.723441615452151 : F1 0.7186942348430048 : Recall 0.723441615452151 : Precision 0.7321982059176192
Score 0.7225636523266022 : F1 0.7168283213015043 : Recall 0.7225636523266022 : Precision 0.7291718664204063
Score 0.7304653204565408 : F1 0.7276668613686322 : Recall 0.7304653204565408 : Precision 0.739163126305324
Score 0.7225636523266022 : F1 0.

array([[336, 210],
       [ 91, 502]])

In [14]:
#Classificador NB
from sklearn.naive_bayes import GaussianNB

#avaliação para NB
realizacoes = 20

#Matriz que vai salvar medidas de cada realização
scoresNB = np.zeros([realizacoes,4])

for item in range(realizacoes):
  X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=random.randrange(0, 101, 2))
  gnb = GaussianNB()
  Y_pred = gnb.fit(X_train, Y_train).predict(X_test)
  scoresNB[item,0] = accuracy_score(Y_test,Y_pred)
  scoresNB[item,1] = f1_score(Y_test,Y_pred, average='weighted')
  scoresNB[item,2] = recall_score(Y_test,Y_pred, average='micro')
  scoresNB[item,3] = precision_score(Y_test,Y_pred, average='weighted')

  print('Score {0} : F1 {1} : Recall {2} : Precision {3}'.format(scoresNB[item,0], scoresNB[item,1], scoresNB[item,2], scoresNB[item,3]))

print('Métricas')
metricsNB = pd.DataFrame(scoresNB, columns=['Accuracy', 'F1', 'Recall', 'Precision'])
print(metricsNB.mean()*100)
confusion_matrix(Y_test,Y_pred)

Score 0.7243195785776997 : F1 0.706873237406591 : Recall 0.7243195785776997 : Precision 0.771948087730541
Score 0.752414398595259 : F1 0.7370520957343626 : Recall 0.752414398595259 : Precision 0.7997133535035492
Score 0.7410008779631255 : F1 0.7249653632948421 : Recall 0.7410008779631255 : Precision 0.7987694093922519
Score 0.7445127304653204 : F1 0.7324692646090126 : Recall 0.7445127304653204 : Precision 0.7951185708330833
Score 0.7418788410886743 : F1 0.7272960262913414 : Recall 0.7418788410886743 : Precision 0.7842744941113701
Score 0.7532923617208077 : F1 0.7391180487766974 : Recall 0.7532923617208077 : Precision 0.8001045088788274
Score 0.7532923617208077 : F1 0.7391180487766974 : Recall 0.7532923617208077 : Precision 0.8001045088788274
Score 0.7497805092186128 : F1 0.7380778024649305 : Recall 0.7497805092186128 : Precision 0.7952011337449602
Score 0.752414398595259 : F1 0.7395204338915301 : Recall 0.752414398595259 : Precision 0.7948229194814626
Score 0.7585601404741001 : F1 0.74

array([[287, 253],
       [ 29, 570]])

In [15]:
#Classificador LR
from sklearn.linear_model import LogisticRegression

from sklearn.preprocessing import MinMaxScaler

#avaliação para LR
realizacoes = 20

#Matriz que vai salvar medidas de cada realização
scoresLR = np.zeros([realizacoes,4])

for item in range(realizacoes):
  X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=random.randrange(0, 101, 2))
  scaler = MinMaxScaler()
  X_train=scaler.fit_transform(X_train)
  X_test=scaler.transform(X_test)
  clf = LogisticRegression(random_state=0).fit(X_train, Y_train)
  Y_pred = clf.predict(X_test)
  scoresLR[item,0] = accuracy_score(Y_test,Y_pred)
  scoresLR[item,1] = f1_score(Y_test,Y_pred, average='weighted')
  scoresLR[item,2] = recall_score(Y_test,Y_pred, average='micro')
  scoresLR[item,3] = precision_score(Y_test,Y_pred, average='weighted')

  print('Score {0} : F1 {1} : Recall {2} : Precision {3}'.format(scoresLR[item,0], scoresLR[item,1], scoresLR[item,2], scoresLR[item,3]))

print('Métricas')
metricsLR = pd.DataFrame(scoresLR, columns=['Accuracy', 'F1', 'Recall', 'Precision'])
print(metricsLR.mean()*100)
confusion_matrix(Y_test,Y_pred)

Score 0.835820895522388 : F1 0.8334750803979666 : Recall 0.835820895522388 : Precision 0.8438754313922716
Score 0.8472344161545216 : F1 0.8453996752425592 : Recall 0.8472344161545216 : Precision 0.8527470786417765
Score 0.8296751536435469 : F1 0.828798695100131 : Recall 0.8296751536435469 : Precision 0.8366748484755829
Score 0.8235294117647058 : F1 0.8217276123643956 : Recall 0.8235294117647058 : Precision 0.8327986714155742
Score 0.845478489903424 : F1 0.8439333233926001 : Recall 0.845478489903424 : Precision 0.8510349303597269
Score 0.820017559262511 : F1 0.8180731060702249 : Recall 0.820017559262511 : Precision 0.8260511587822387
Score 0.8296751536435469 : F1 0.82810503421757 : Recall 0.8296751536435469 : Precision 0.8349840668331754
Score 0.8446005267778753 : F1 0.8433529136755955 : Recall 0.8446005267778753 : Precision 0.8513269928138979
Score 0.8331870061457419 : F1 0.8305476439842913 : Recall 0.8331870061457419 : Precision 0.8414860515854361
Score 0.8296751536435469 : F1 0.82797

array([[393, 134],
       [ 58, 554]])

In [16]:
#Classificador RF
from sklearn.ensemble import RandomForestClassifier

#avaliação para RF
realizacoes = 20

#Matriz que vai salvar medidas de cada realização
scoresRF = np.zeros([realizacoes,4])

for item in range(realizacoes):
  X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=random.randrange(0, 101, 2))

  clf = RandomForestClassifier(n_estimators=10)
  clf = clf.fit(X_train, Y_train)
  Y_pred = clf.predict(X_test)
  scoresRF[item,0] = accuracy_score(Y_test,Y_pred)
  scoresRF[item,1] = f1_score(Y_test,Y_pred, average='weighted')
  scoresRF[item,2] = recall_score(Y_test,Y_pred, average='weighted')
  scoresRF[item,3] = precision_score(Y_test,Y_pred, average='weighted')

  print('Score {0} : F1 {1} : Recall {2} : Precision {3}'.format(scoresRF[item,0], scoresRF[item,1], scoresRF[item,2], scoresRF[item,3]))

print('Métricas')
metricsRF = pd.DataFrame(scoresRF, columns=['Accuracy', 'F1', 'Recall', 'Precision'])
print(metricsRF.mean()*100)
confusion_matrix(Y_test,Y_pred)

Score 0.7743634767339772 : F1 0.7741272028085531 : Recall 0.7743634767339772 : Precision 0.7741607589705012
Score 0.7594381035996488 : F1 0.7585493059796878 : Recall 0.7594381035996488 : Precision 0.7597490164658381
Score 0.7778753292361721 : F1 0.7775998466159781 : Recall 0.7778753292361721 : Precision 0.7776727623042946
Score 0.7734855136084284 : F1 0.7726486165794142 : Recall 0.7734855136084284 : Precision 0.7739400672920823
Score 0.7761194029850746 : F1 0.7758014284124414 : Recall 0.7761194029850746 : Precision 0.7763596370130569
Score 0.7647058823529411 : F1 0.7644664587268812 : Recall 0.7647058823529411 : Precision 0.7643977040718055
Score 0.7480245829675154 : F1 0.7470484876645954 : Recall 0.7480245829675154 : Precision 0.7486479302255982
Score 0.7831431079894644 : F1 0.7827556592865967 : Recall 0.7831431079894644 : Precision 0.7830113209443139
Score 0.7831431079894644 : F1 0.7827477862487021 : Recall 0.7831431079894644 : Precision 0.7829957039801981
Score 0.7761194029850746 : F

array([[393, 139],
       [109, 498]])

In [20]:
#Classificador MLP
from sklearn.neural_network import MLPClassifier

#avaliação para MLP
realizacoes = 20

#Matriz que vai salvar medidas de cada realização
scoresMLP = np.zeros([realizacoes,4])

for item in range(realizacoes):
  X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=random.randrange(0, 101, 2))

  clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(10, 2), random_state=1)
  clf.fit(X_train, Y_train)
  Y_pred = clf.predict(X_test)

  scoresMLP[item,0] = accuracy_score(Y_test,Y_pred)
  scoresMLP[item,1] = f1_score(Y_test,Y_pred, average='weighted')
  scoresMLP[item,2] = recall_score(Y_test,Y_pred, average='weighted')
  scoresMLP[item,3] = precision_score(Y_test,Y_pred, average='weighted')

  print('Score {0} : F1 {1} : Recall {2} : Precision {3}'.format(scoresMLP[item,0], scoresMLP[item,1], scoresMLP[item,2], scoresMLP[item,3]))

print('Métricas')
metricsMLP = pd.DataFrame(scoresMLP, columns=['Accuracy', 'F1', 'Recall', 'Precision'])
print(metricsMLP.mean()*100)
confusion_matrix(Y_test,Y_pred)

Score 0.684811237928007 : F1 0.6563421065181598 : Recall 0.684811237928007 : Precision 0.7470011636495394
Score 0.5794556628621598 : F1 0.4810708017314607 : Recall 0.5794556628621598 : Precision 0.7494075461367614
Score 0.746268656716418 : F1 0.7263339201285128 : Recall 0.746268656716418 : Precision 0.8175662911547787
Score 0.6962247585601404 : F1 0.6723589495409783 : Recall 0.6962247585601404 : Precision 0.7581609970388085
Score 0.66900790166813 : F1 0.645861272485389 : Recall 0.66900790166813 : Precision 0.7091508573660829
Score 0.5856014047410009 : F1 0.47243327574895033 : Recall 0.5856014047410009 : Precision 0.7561452039112396
Score 0.5759438103599649 : F1 0.4677921334608358 : Recall 0.5759438103599649 : Precision 0.7345153319836363
Score 0.6136962247585601 : F1 0.6027861188719232 : Recall 0.61369622475856 : Precision 0.6193339826887662
Score 0.7216856892010536 : F1 0.702240198744566 : Recall 0.7216856892010536 : Precision 0.7741999444842187
Score 0.5873573309920983 : F1 0.4761073

array([[247, 298],
       [ 29, 565]])

In [18]:
#Classificador SVM
from sklearn import svm

#avaliação para SVM
realizacoes = 20

#Matriz que vai salvar medidas de cada realização
scoresSVM = np.zeros([realizacoes,4])

for item in range(realizacoes):
  X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=random.randrange(0, 101, 2))

  clf = svm.SVC()
  clf.fit(X_train, Y_train)
  Y_pred = clf.predict(X_test)

  scoresSVM[item,0] = accuracy_score(Y_test,Y_pred)
  scoresSVM[item,1] = f1_score(Y_test,Y_pred, average='weighted')
  scoresSVM[item,2] = recall_score(Y_test,Y_pred, average='weighted')
  scoresSVM[item,3] = precision_score(Y_test,Y_pred, average='weighted')

  print('Score {0} : F1 {1} : Recall {2} : Precision {3}'.format(scoresSVM[item,0], scoresSVM[item,1], scoresSVM[item,2], scoresSVM[item,3]))

print('Métricas')
metricsSVM = pd.DataFrame(scoresSVM, columns=['Accuracy', 'F1', 'Recall', 'Precision'])
print(metricsSVM.mean()*100)
confusion_matrix(Y_test,Y_pred)

Score 0.6874451273046532 : F1 0.6487082982263885 : Recall 0.6874451273046532 : Precision 0.7802481427509712
Score 0.6733977172958736 : F1 0.6341200571536779 : Recall 0.6733977172958736 : Precision 0.7766774470876638
Score 0.6611062335381914 : F1 0.6139000777239552 : Recall 0.6611062335381914 : Precision 0.7678426436588144
Score 0.6874451273046532 : F1 0.6518644094427541 : Recall 0.6874451273046532 : Precision 0.7897289782386706
Score 0.6733977172958736 : F1 0.6341200571536779 : Recall 0.6733977172958736 : Precision 0.7766774470876638
Score 0.6733977172958736 : F1 0.6330938500400225 : Recall 0.6733977172958736 : Precision 0.7758523983698897
Score 0.6804214223002634 : F1 0.6440962565627303 : Recall 0.6804214223002634 : Precision 0.7829221836985889
Score 0.6927129060579456 : F1 0.6546429185258648 : Recall 0.6927129060579456 : Precision 0.7915588632060849
Score 0.6786654960491659 : F1 0.6392960391445197 : Recall 0.6786654960491659 : Precision 0.7876274734922671
Score 0.6953467954345918 : F

array([[187, 347],
       [  8, 597]])

In [21]:
print('\n',metricsKNN.mean()*100)
print('\n',metricsNB.mean()*100)
print('\n',metricsLR.mean()*100)
print('\n',metricsRF.mean()*100)
print('\n',metricsMLP.mean()*100)
print('\n',metricsSVM.mean()*100)


 Accuracy     73.428446
F1           73.033598
Recall       73.428446
Precision    74.050209
dtype: float64

 Accuracy     74.903424
F1           73.509343
Recall       74.903424
Precision    79.418180
dtype: float64

 Accuracy     83.318701
F1           83.144458
Recall       83.318701
Precision    83.921092
dtype: float64

 Accuracy     76.931519
F1           76.880764
Recall       76.931519
Precision    76.947760
dtype: float64

 Accuracy     68.604039
F1           64.793321
Recall       68.604039
Precision    75.807500
dtype: float64

 Accuracy     68.103600
F1           64.211084
Recall       68.103600
Precision    78.050487
dtype: float64
